### ISSUE TITLE
if the variable is false at the start why still show it?

### ISSUE THREAD

**Issue by Dj-jom2x** [ibenjelloun/ngx-animations#5]
if the variable is false at the start why still show it?.. 
it does work but.. on first load.. the animIf should behave like ngif.. it wont show unless if its false.. not when you click it first then it will triggered

**Comment by Dj-jom2x** [comment]
https://stackblitz.com/edit/ngx-animations example this .. if you set it to false the variable.. it should hide.. at first ...  the reason for this because i cant use ngif ```Can't have multiple template bindings on one element. Use only one attribute prefixed with etc.``` ..

**Comment by ibenjelloun** [comment]
Fixed in 2.2.6.
