### ISSUE TITLE
user Animate.css V4.x

### ISSUE THREAD

**Issue by fssgh** [ibenjelloun/ngx-animations#9]
When upgrading to user Animate.css V4.x？

**Comment by ibenjelloun** [comment]
Hi @fssgh ,
`ngx-animations` has no dependencies to Animate.css, what do you feel is missing from Animate.css V4.x ?

**Comment by fssgh** [comment]
Animate.css V4.x has more animation effects

**Comment by ibenjelloun** [comment]
I'll add that to my todo list.
If you want to have the new animations you can use the custom animation feature to add them here is the documentation link : https://github.com/ibenjelloun/ngx-animations/tree/master/libs/ngx-animations#add-custom-animations-to-the-existing-animations

**Comment by ibenjelloun** [comment]
Missing animations from Animate.css : 

- backInDown
- backInLeft
- backInRight
- backInUp
- backOutDown
- backOutLeft
- backOutRight
- backOutUp

**Comment by ibenjelloun** [comment]
Fixed : https://github.com/ibenjelloun/ngx-animations/commit/4b3771f20170e7a1a59f14442f54b6f12f820a6f
ngx-animations@5.0.4
